# 前端 Dockerfile
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN npm config set registry https://mirrors.tencent.com/npm/
RUN npm install && npm run build
 
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 
