services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: resume-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - resume-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: resume-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - resume-network

  nginx:
    image: nginx:latest
    container_name: resume-nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge