services:
  # MongoDB 数据库服务
  mongodb:
    image: mongo:5.0
    container_name: resume-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-resumedb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-Wangzhaoyu011207}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-resume_builder}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb_dump.tar.gz:/docker-entrypoint-initdb.d/mongodb_dump.tar.gz:ro
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - resume-network
    # 资源限制 - 适合2核4GB环境
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Redis 缓存服务
  redis:
    image: redis:7-alpine
    container_name: resume-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - resume-network
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: resume-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8081}:8081"
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME:-resumedb}:${MONGODB_PASSWORD:-Wangzhaoyu011207}@mongodb:27017/${MONGODB_DATABASE:-resume_builder}?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8081
      - FRONTEND_URL=https://${DOMAIN_NAME:-www.flexresume.me}
      - DOMAIN_NAME=${DOMAIN_NAME:-www.flexresume.me}
      - CORS_ALLOWED_ORIGINS=https://www.flexresume.me,https://flexresume.me,http://${SERVER_IP:-45.76.146.146}:${FRONTEND_PORT:-8080},http://localhost:3000
    env_file:
      - config.env
    depends_on:
      - mongodb
      - redis
    networks:
      - resume-network
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_API_URL=http://${SERVER_IP:-101.34.235.142}:${BACKEND_PORT:-8081}
        - REACT_APP_SERVER_IP=${SERVER_IP:-101.34.235.142}
    container_name: resume-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - REACT_APP_API_URL=http://${SERVER_IP:-101.34.235.142}:${BACKEND_PORT:-8081}
      - REACT_APP_SERVER_IP=${SERVER_IP:-101.34.235.142}
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT:-8081}
      - REACT_APP_FRONTEND_PORT=${FRONTEND_PORT:-8080}
    env_file:
      - config.env
    networks:
      - resume-network
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  nginx:
    image: nginx:alpine
    container_name: resume-nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "${NGINX_PORT:-80}:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    environment:
      - SERVER_IP=${SERVER_IP:-101.34.235.142}
      - DOMAIN_NAME=${DOMAIN_NAME:-www.flexresume.me}
      - BACKEND_PORT=${BACKEND_PORT:-8081}
    env_file:
      - config.env
    networks:
      - resume-network
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

volumes:
  redis_data:
    driver: local

networks:
  resume-network:
    driver: bridge